version: "3.9"

services:
  db_clients_registry:
    container_name: db_clients_registry
    image: postgres:14-alpine
    ports:
      - 5436:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    container_name: api
    build: .
    command: sh -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db_clients_registry
    depends_on:
      db_clients_registry:
        condition: service_healthy
    volumes:
      - .:/app
